os:
  - osx
  - linux
dist: trusty
osx_image: xcode8.3
language: node_js
node_js:
  - '6'
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                                   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mosquitto                                        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew services start mosquitto                                 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa -y  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y                                      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install mosquitto -y                           ; fi
before_script:
  - |
    if [ $TRAVIS_OS_NAME != osx ]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      sleep 3
    fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libsecret-1-dev
      - gnome-keyring
      - libavahi-compat-libdnssd-dev
install:
- nvm install 6
- npm install

script:
- npm test


#dist: trusty
#language: node_js
#node_js:
#  - '6'
#before_install:
#  - sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa -y
#  - sudo apt-get update -y
#  - sudo apt-get install mosquitto -y
#  - sudo apt-get install libsecret-1-dev -y
#  - sudo apt-get install libavahi-compat-libdnssd-dev -y
