dist: trusty
language: node_js
node_js:
  - '6'
before_install:
  - sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa -y
  - sudo apt-get update -y
  - sudo apt-get install mosquitto -y
  - sudo apt-get install libsecret-1-dev -y
  - sudo apt-get install libavahi-compat-libdnssd-dev -y
  - sudo apt-get install gnome-keyring -y
  - sudo apt-get install xvfb -y
before_script:
  - |
    if [ $TRAVIS_OS_NAME != osx ]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      sleep 3
      dbus-launch /usr/bin/python -c "import gnomekeyring;gnomekeyring.create_sync('login', '');"
    fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libsecret-1-dev