os: osx
osx_image: xcode8.3
language: node_js
node_js:
  - '6'
before_install:
  - brew update
  - brew install mosquitto
  - brew services start mosquitto

install:
- nvm install 6
- npm install

script:
- npm test
